spring:
  datasource:
    url: jdbc:postgrsql://localhost:5432/whatsapp_clone
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-url: http://localhost:9090/realms/whatsapp-clone
  servlet:
    multipart:
      max-file-size: 50MB

application:
  file:
    uploads:
      media-output.path: ./uploads


